import { Link } from "react-router-dom"
import { OPERATOR_NAME } from "./legal"
import { useSeo } from "@/lib/seo"
import {
  ContactLine,
  ExternalLink,
  LegalLayout,
  LegalSection,
} from "./LegalLayout"

export function PrivacyPolicyPage() {
  useSeo({
    title: "Privacy Policy - RosterMe",
    description:
      "How RosterMe collects, uses, and protects organizer and volunteer data.",
    path: "/privacy-policy",
  })
  return (
    <LegalLayout
      title="Privacy Policy"
      intro={`We do not add people to ${OPERATOR_NAME} without permission. A person joins when they create an organizer account themselves, or when they sign up as a volunteer through an invite link. This policy explains in plain terms what we collect, why we collect it, who we share it with, and how to ask for access or deletion.`}
      sibling={{ to: "/terms-of-service", label: "Terms of Service" }}
    >
      <LegalSection id="who-is-responsible" title="1. Who is responsible">
        <p>
          {OPERATOR_NAME} (“we”, “us”) decides how the service runs and is the{" "}
          <strong>data controller</strong> for organizer accounts and for
          operating the service. <ContactLine />
        </p>
        <p>
          For volunteer signup data (names, email addresses, and signup
          status), we act as a <strong>processor for the organizer</strong>{" "}
          running the event. The organizer decides which events to run and who
          to invite. We store and email that data only to operate their roster.
          Volunteers can exercise their rights against the organizer or against
          us, as described in section 9.
        </p>
      </LegalSection>

      <LegalSection
        id="what-we-collect"
        title="2. What we collect and where it comes from"
      >
        <p>
          <strong>Organizers.</strong> When you create an account, our login
          provider Clerk shares your account identity with us: a Clerk user ID
          and the email address on your account. We also store the organization
          name and the events, time slots, and invite links you create. Source:
          you, via Clerk.
        </p>
        <p>
          <strong>Volunteers.</strong> When you sign up through an invite link,
          we collect the name and email address you type in, the slot you
          chose, your signup status (pending, confirmed, cancelled, or
          removed), and timestamps (created, confirmed, reminder sent). We store
          a hashed form of your personal manage token so we can recognize your
          manage link without keeping a readable copy of it. Source: you, via
          the signup form.
        </p>
        <p>
          <strong>Email records.</strong> To deliver confirmations, reminders,
          and cancellation notices reliably, each signup email is kept as a
          delivery record (recipient, subject, message text, and any calendar
          file attached) until it has been sent. Source: generated by the
          service when you sign up or run an event.
        </p>
        <p>
          <strong>Technical data.</strong> Our servers process standard data
          needed to run the service, such as IP addresses and request logs.
          Source: automatic, when you use the site. We do not use advertising
          trackers and we do not sell personal data.
        </p>
      </LegalSection>

      <LegalSection id="how-we-use" title="3. How we use your information">
        <p>
          We use personal data only to run the roster service. In short:
        </p>
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>To run the roster.</strong> Storing events, slots, and
            signups, enforcing slot capacity, and showing organizers their
            volunteer list.
          </li>
          <li>
            <strong>To confirm signups and stop abuse.</strong> Email
            confirmation links keep mistyped and fake addresses off rosters.
            Hashed manage tokens let volunteers manage their own signups
            securely.
          </li>
          <li>
            <strong>To send service emails.</strong> Confirmations, reminders
            around 24 hours before a shift, and cancellation notices.
            Volunteers get these because they asked to sign up. Marketing emails
            are never sent to volunteers.
          </li>
          <li>
            <strong>To keep accounts safe.</strong> Checking organizer identity
            through Clerk and protecting accounts against misuse.
          </li>
          <li>
            <strong>To follow the law.</strong> Keeping records where required
            and responding to lawful requests.
          </li>
        </ul>
        <p>
          For readers in the EU or UK: the legal bases are contract (running
          the service you asked for), consent (reminder emails tied to a signup
          you can cancel), legitimate interests (security and abuse
          prevention), and legal obligation (records the law requires).
        </p>
      </LegalSection>

      <LegalSection id="sharing" title="4. Who we share data with">
        <p>
          We share personal data only as needed to run the service. We never
          sell it and never share it for someone else’s marketing:
        </p>
        <p>
          <strong>Clerk, for organizer login (processor).</strong> Sign-in is
          handled by Clerk, Inc. (USA). What Clerk sees: your login identity
          (Clerk user ID, email address, session data) so we can check who you
          are and which organization you own. Clerk processes this under its{" "}
          <ExternalLink href="https://clerk.com/legal/privacy">
            privacy policy
          </ExternalLink>{" "}
          with processor terms in its{" "}
          <ExternalLink href="https://clerk.com/legal">legal hub</ExternalLink>.
          Clerk does not sell personal data. It uses infrastructure providers
          to host the login service and discloses data only to provide the
          service, for security, for legal compliance, or with consent.
        </p>
        <p>
          <strong>Resend, for email delivery (processor).</strong> Volunteer
          emails are sent by Resend (Plus Five Five, Inc., USA) on our behalf.
          What Resend sees per email: the recipient address, subject, message
          text (which includes the volunteer name, event details, and manage
          link), and any calendar file attached. Resend processes this under
          its{" "}
          <ExternalLink href="https://resend.com/legal/privacy-policy">
            privacy policy
          </ExternalLink>
          , with processor terms in its{" "}
          <ExternalLink href="https://resend.com/legal/dpa">
            Data Processing Addendum
          </ExternalLink>{" "}
          and infrastructure providers listed in its{" "}
          <ExternalLink href="https://resend.com/legal/subprocessors">
            subprocessor list
          </ExternalLink>
          . Resend acts on our instructions and does not use email content for
          its own marketing.
        </p>
        <p>
          <strong>Organizers see their own roster.</strong> An organizer can see
          the names, email addresses, and statuses of volunteers who signed up
          for their events, and can export that list. By signing up, volunteers
          accept that the organizer running the event receives the details they
          enter. Organizers must use roster data only to run their events (see
          our Terms of Service) and must look after any copies they download.
        </p>
        <p>
          <strong>Hosting.</strong> Data is stored in our PostgreSQL database
          wherever this {OPERATOR_NAME} instance is hosted. Nobody else gets
          personal data unless the law requires it or it is strictly needed to
          keep the service running. If that happens, we will tell you where the
          law allows it.
        </p>
        <p>
          <strong>Business transfers.</strong> If we are acquired or merged, or
          our assets are sold, your information may move to the new owner as
          part of that deal.
        </p>
      </LegalSection>

      <LegalSection id="transfers" title="5. International transfers">
        <p>
          Clerk and Resend are based in the United States, so organizer login
          data and volunteer email content are sent to and processed in the US.
          Both providers offer standard contractual clauses for such transfers:
          Clerk through its{" "}
          <ExternalLink href="https://clerk.com/legal">legal hub</ExternalLink>{" "}
          and Resend through its{" "}
          <ExternalLink href="https://resend.com/legal/dpa">
            Data Processing Addendum
          </ExternalLink>
          . Where the service database itself is hosted also decides where
          roster data sits, so organizers in the EU or UK should note this for
          their own records.
        </p>
      </LegalSection>

      <LegalSection id="cookies" title="6. Cookies">
        <p>
          We use only cookies that are strictly needed to run the service,
          mainly Clerk session and security cookies that keep organizers signed
          in. We do not set advertising or cross-site tracking cookies, and
          volunteers who browse or sign up through a public invite link are not
          tracked for advertising.
        </p>
        <p>
          Which cookies Clerk sets is described in{" "}
          <ExternalLink href="https://clerk.com/legal/privacy">
            Clerk’s privacy policy
          </ExternalLink>
          . You can block cookies in your browser, but organizer sign-in will
          not work without the strictly needed ones.
        </p>
      </LegalSection>

      <LegalSection id="retention" title="7. How long we keep data">
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <strong>Volunteer signups</strong> stay part of the organizer’s
            roster history until the organizer deletes the event or
            organization, or a deletion request is granted.
          </li>
          <li>
            <strong>Email delivery records</strong> are kept until sent, plus a
            short period to debug delivery failures, then removed in routine
            cleanup.
          </li>
          <li>
            <strong>Organizer accounts</strong> (organization name, Clerk user
            ID) are kept while the account exists and removed within a
            reasonable period after deletion, except where the law requires
            longer storage.
          </li>
          <li>
            Copies an organizer downloaded are the organizer’s responsibility.
            Deleting data in {OPERATOR_NAME} does not delete copies already
            exported.
          </li>
        </ul>
      </LegalSection>

      <LegalSection id="security" title="8. Security">
        <p>
          We protect personal data with transport encryption, ownership checks
          on every admin request, hashed manage tokens (so a database copy
          alone cannot rebuild manage links), and limited access to
          credentials. No system is fully secure. If you suspect misuse of a
          manage link or account, cancel it or rotate it and contact us right
          away.
        </p>
      </LegalSection>

      <LegalSection id="rights" title="9. Your rights">
        <p>
          You may ask for access to or deletion of your personal information at
          any time. Contact us at the address in section 1, or the organization
          that ran the event. We will reply within one month. We may need to
          verify your identity first, for example by confirming you can open
          the signup email address.
        </p>
        <p>
          The fastest route for volunteers: open your manage link to review
          your signup, or cancel it to release your spot and stop reminders.
          For anything else, including a copy of your data or deletion of a
          signup made in error, contact us and we will help.
        </p>
        <p>
          <strong>EU, EEA, and UK residents.</strong> You have the right to
          access your data, fix mistakes, erase it, restrict or object to
          processing, take it elsewhere (portability), and withdraw consent
          where consent applies. You can also complain to your supervisory
          authority.
        </p>
        <p>
          <strong>California residents.</strong> You have the right to know what
          personal information we collect, use, and disclose (described in
          sections 2 to 4 above), to delete and correct it, and to be free from
          discrimination for exercising these rights. To sum up for CCPA
          purposes: categories collected are identifiers (name, email, account
          IDs), event signup records, and technical data (IP, logs); sources
          are you, Clerk, and automatic logs; purposes are running rosters,
          login, service emails, security, and legal compliance;           disclosed to
          the event’s organization, Clerk, and Resend. We do not sell personal
          information and do not share it for cross-context behavioral
          advertising, so there is nothing to opt out of. You may use an
          authorized agent with your written permission.
        </p>
        <p>
          We keep some information where the law allows or requires it, for
          example for security, fraud prevention, and proper record keeping.
        </p>
      </LegalSection>

      <LegalSection id="children" title="10. Children">
        <p>
          {OPERATOR_NAME} is not aimed at children under 16, and volunteers
          under 16 may only sign up with a parent or guardian involved (see our{" "}
          <Link
            to="/terms-of-service"
            className="font-medium text-primary underline underline-offset-4"
          >
            Terms of Service
          </Link>
          ). If you think a child’s data was submitted without proper consent,
          contact us and we will delete it.
        </p>
      </LegalSection>

      <LegalSection id="changes" title="11. Changes to this policy">
        <p>
          If we change this policy in a material way, we will post the updated
          version on this page with a new “last updated” date and, where the
          change is significant, give extra notice in the app. The version
          published here is the one in force.
        </p>
      </LegalSection>
    </LegalLayout>
  )
}
